//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAddressDet
    {
        public int AddressID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int EmployeeID { get; set; }
        public int StateID { get; set; }
        public int PinCode { get; set; }
    
        public virtual EmployeeMst EmployeeMst { get; set; }
        public virtual StateMst StateMst { get; set; }
    }
}
